activos/urls.py
from django.urls import path

from .views import get, retrieve, update, post, delete

app_name = 'activos'

urlpatterns = [
    path('', get, name='get'),
    path('crear/', post, name='create'),
    path('<int:pk>/', update, name='update'),
    path('<int:pk>/detalle/', retrieve, name='detail'),
    path('<int:pk>/eliminar/', delete, name='delete'),
    
]

clientes/urls.py
from django.urls import path

from .views import get, retrieve, update, post, delete

app_name = 'clientes'

urlpatterns = [
    path('', get, name='get'),
    path('crear/', post, name='create'),
    path('<int:cliente_id>/', update, name='update'),
    path('<int:cliente_id>/detalle/', retrieve, name='detail'),
    path('<int:cliente_id>/eliminar/', delete, name='delete'),
    
]

equipos/urls.py
from django.urls import path

from .views import EquiposListView, EquiposCreateView, EquiposUpdateView, EquiposDetailView, EquipoDeleteview

app_name = 'equipos'

urlpatterns = [
    path('', EquiposListView.as_view(), name='get'),
    path('crear/', EquiposCreateView.as_view(), name='create'),
    path('<int:pk>/', EquiposUpdateView.as_view(), name='update'),
    path('<int:pk>/detalle/', EquiposDetailView.as_view(), name='detail'),
    path('<int:pk>/eliminar/', EquipoDeleteview.as_view(), name='delete'),
    
]

miniadmin_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),
    path('activos/', include('activos.urls')),
    path('equipos/', include('equipos.urls')),
]

activos/models.py
from enum import unique
from random import choices
from django.db import models

# Create your models here.

class Activos(models.Model):
    class TipoActivo(models.IntegerChoices):
        PERSONAL = 0
        VEHICULAR = 1

    nombre = models.CharField(max_length=50, unique=True)
    placa = models.CharField(max_length=50, null=True)
    tipo_activo = models.IntegerField(choices=TipoActivo.choices)
    cliente = models.ForeignKey('clientes.Clientes', on_delete=models.CASCADE, related_name='clientes_activos_set')

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = 'Activo'
        verbose_name_plural = 'Activos'

clientes/models.py
from django.db import models

# Create your models here.

class Clientes(models.Model):
    nombre = models.CharField(max_length=50)
    nit = models.CharField(max_length=50)
    nombre_contacto = models.CharField(max_length=80)
    telefono = models.PositiveIntegerField()
    direccion = models.CharField(max_length=100)
    correo = models.EmailField()

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        unique_together = ('nombre', 'nit')

equipos/models.py
from enum import unique
from django.db import models

# Create your models here.
class Equipo(models.Model):
    imei = models.CharField(max_length=16, unique=True)
    simcard = models.PositiveIntegerField(null=True)
    operador = models.CharField(max_length=50, null=True)
    activo = models.ForeignKey('activos.Activos', on_delete=models.SET_NULL, null=True, related_name='equipos_activo_set')
    cliente = models.ForeignKey('clientes.Clientes', on_delete=models.CASCADE, related_name='equipos_cliente_set')

    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'

equipos/forms.py
from django.forms import ModelForm, fields

from equipos.models import Equipo


class EquiposForm(ModelForm):

    class Meta:
        model = Equipo
        fields = '__all__'

activos/views.py
from django.shortcuts import render, get_object_or_404

from activos.models import Activos
from clientes.models import Clientes


def get(request):
    queryset = Activos.objects.all()
    context = {'lista': queryset}
    return render(request, 'activos/activos.html', context)


def retrieve(request, pk):
    activo = get_object_or_404(Activos, pk=pk)
    return render(request, 'activos/activo-detalle.html', {'instancia': activo})


def update(request, pk):
    activo = get_object_or_404(Activos, pk=pk)
    if request.method == 'POST':
        activo.nombre = request.POST['nombre']
        activo.placa = request.POST.get('placa', None)
        activo.tipo_activo = request.POST['tipo_activo']
        activo.cliente_id = request.POST['cliente_id']

        activo.save()

    clientes = Clientes.objects.only('id', 'nombre')

    return render(request, 'activos/activo-actualizar.html', {'instancia': activo, 'clientes': clientes})


def post(request):
    if request.method == 'POST':
        Activos.objects.create(
            nombre=request.POST['nombre'],
            placa=request.POST.get('placa', None),
            tipo_activo=request.POST['tipo_activo'],
            cliente_id=request.POST['cliente_id'],
        )

    clientes = Clientes.objects.only('id', 'nombre')
        
    return render(request, 'activos/activo-crear.html', {'clientes': clientes}) 


def delete(request, pk):
    activo = get_object_or_404(Activos, pk=pk)
    activo.delete()
    return get(request)

clientes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from clientes.models import Clientes
from django.http import HttpResponseRedirect
from django.urls import reverse


def get(request):
    queryset = Clientes.objects.all()
    context = {'lista_clientes': queryset}
    return render(request, 'clientes/clientes.html', context)


def retrieve(request, cliente_id):
    cliente = get_object_or_404(Clientes, pk=cliente_id)
    return render(request, 'clientes/cliente-detalle.html', {'instancia': cliente})


def update(request, cliente_id):
    cliente = get_object_or_404(Clientes, pk=cliente_id)
    if request.method == 'POST':
        cliente.nombre = request.POST['nombre']
        cliente.nit = request.POST['nit']
        cliente.nombre_contacto = request.POST['nombre_contacto']
        cliente.telefono = request.POST['tel']
        cliente.direccion = request.POST['direccion']
        cliente.correo = request.POST['correo']

        cliente.save()

    return render(request, 'clientes/cliente-actualizar.html', {'instancia': cliente})


def post(request):
    print(request.method)
    print(request.POST)
    if request.method == 'POST':
        Clientes.objects.create(
            nombre=request.POST['nombre'],
            nit=request.POST['nit'],
            nombre_contacto=request.POST['nombre_contacto'],
            telefono=request.POST['tel'],
            direccion=request.POST['direccion'],
            correo=request.POST['correo']
        )
        
    return render(request, 'clientes/cliente-crear.html') 


def delete(request, cliente_id):
    cliente = get_object_or_404(Clientes, pk=cliente_id)
    cliente.delete()
    return HttpResponseRedirect(reverse('clientes:get'))

equipos/views.py
from django.shortcuts import render

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from equipos.forms import EquiposForm
from equipos.models import Equipo
from django.db.models import QuerySet
from django.urls import reverse_lazy


# Create your views here.
class EquiposListView(ListView):
    model = Equipo
    template_name = 'equipos/equipos.html'

    def get_queryset(self) -> QuerySet[Equipo]:
        return self.model.objects.only('id', 'imei')


class EquiposCreateUpdateViewMixin:
    model = Equipo
    form_class = EquiposForm
    # fields = ['imei', 'simcard', 'operador', 'activo', 'cliente']
    template_name = 'equipos/equipo-crear.html'
    success_url = reverse_lazy('equipos:get')


class EquiposCreateView(EquiposCreateUpdateViewMixin, CreateView):
    pass


class EquiposUpdateView(EquiposCreateUpdateViewMixin, UpdateView):
    pass


class EquiposDetailView(DetailView):
    model = Equipo
    fields = ['imei', 'simcard', 'activo', 'cliente']
    template_name = 'equipos/equipo-detalle.html'
    context_object_name = 'instancia'


class EquipoDeleteview(DeleteView):
    model = Equipo
    success_url = reverse_lazy('equipos:get')

templates/activos/activo-actualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activos - {{ instancia.nombre}}</title>
</head>
<body>
    <h1>Actualizar Activo</h1>
    <br>

    <form action="{% url 'activos:update' instancia.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ instancia.nombre }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="nombre">Nombre del Activo: </label>
            <input type="text" name="nombre" id="nombre" value="{{ instancia.nombre }}"><br><br>
            
            <label for="placa">Placa del Activo: </label>
            <input type="text" name="placa" id="placa" value="{{ instancia.placa }}"><br><br>   
            
            <h4>Tipo de Activo:</h4>
            <input type="radio" name="tipo_activo" id="personal" value="0">    
            <label for="personal">Personal</label>

            <input type="radio" name="tipo_activo" id="vehicular" value="1">
            <label for="vehicular">Vehicular</label> <br>

            <h4>Cliente:</h4>
            <select name="cliente_id" id="cliente">
                {% for cl in clientes %}
                <option value="{{cl.id}}">{{cl.nombre}}</option>
                {% endfor %}
            </select> 

        </fieldset>
        <input type="submit" value="Actualizar">
        <a href="{% url 'activos:get' %}">Lista</a>
        </form>
</body>
</html>

templates/activos/activo-crear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activos</title>
</head>
<body>
    <h1>Crear Activo</h1>
    <br>

    <form action="{% url 'activos:create' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Nuevo Activo</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="nombre">Nombre del Activo: </label>
            <input type="text" name="nombre" id="nombre" value=""><br><br>
            
            <label for="placa">Placa: </label>
            <input type="text" name="placa" id="placa" value=""><br><br> 
            
            
            <h4>Tipo de Activo:</h4>
            <input type="radio" name="tipo_activo" id="personal" value="0">    
            <label for="personal">Personal</label>

            <input type="radio" name="tipo_activo" id="vehicular" value="1">
            <label for="vehicular">Vehicular</label> <br>
            
            <h4>Cliente:</h4>
            <select name="cliente_id" id="cliente">
                {% for cl in clientes %}
                <option value="{{cl.id}}">{{cl.nombre}}</option>
                {% endfor %}
            </select>

        </fieldset>
        <input type="submit" value="Crear">
        </form>
        <a href="{% url 'activos:get' %}">Ir a la lista</a>
</body>
</html>

templates/activos/activo-detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activo - {{ instancia.nombre }}</title>
</head>
<body>
    <h1>Instancia de Activo</h1>
    <br>

    <ul>
        <li><a href="{% url 'activos:update' instancia.id %}">{{ instancia.nombre }}</a></li>
        <li>{{ instancia.placa }}</li>
        <li>{{ instancia.tipo_activo }}</li>
        <li>{{ instancia.cliente }}</li>
    </ul>

</body>
</html>

templates/activos/activos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activos</title>
</head>
<body>
    <h1>Lista de Activos</h1>
    <br>
    {% if lista %}
        <ul>
        {% for cl in lista %}
            <li><a href="{% url 'activos:detail' cl.id %}">{{ cl.nombre }}     <a href="{% url 'activos:delete' cl.id %}">X</a> </a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No existen clientes.</p>
    {% endif %}

    <a href="{% url 'activos:create' %}">Crear Activo</a>
</body>
</html>

templates/clientes/cliente-actualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cliente - {{ instancia.nombre}}</title>
</head>
<body>
    <h1>Actualizar Cliente</h1>
    <br>

    <form action="{% url 'clientes:update' instancia.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ instancia.nombre }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="nombre">Nombre del Cliente: </label>
            <input type="text" name="nombre" id="nombre" value="{{ instancia.nombre }}"><br><br>
            
            <label for="nit">NIT: </label>
            <input type="text" name="nit" id="nit" value="{{ instancia.nit }}"><br><br>     

            <label for="nombre_contacto">Nombre del contacto: </label>
            <input type="text" name="nombre_contacto" id="nombre_contacto" value="{{ instancia.nombre_contacto }}"><br><br>     

            <label for="tel">Número de teléfono: </label>
            <input type="number" name="tel" id="tel" value="{{ instancia.telefono }}"><br><br>     

            <label for="direccion">Dirección: </label>
            <input type="text" name="direccion" id="direccion" value="{{ instancia.direccion }}"><br><br>

            <label for="correo">Correo electrónico: </label>
            <input type="email" name="correo" id="correo" value="{{ instancia.correo }}"><br><br>     

        </fieldset>
        <input type="submit" value="Actualizar">
        <a href="{% url 'clientes:get' %}">Lista</a>
        </form>
</body>
</html>

templates/clientes/cliente-crear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cliente</title>
</head>
<body>
    <h1>Crear Cliente</h1>
    <br>

    <form action="{% url 'clientes:create' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Nuevo Cliente</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label for="nombre">Nombre del Cliente: </label>
            <input type="text" name="nombre" id="nombre" value=""><br><br>
            
            <label for="nit">NIT: </label>
            <input type="text" name="nit" id="nit" value=""><br><br>     

            <label for="nombre_contacto">Nombre del contacto: </label>
            <input type="text" name="nombre_contacto" id="nombre_contacto" value=""><br><br>     

            <label for="tel">Número de teléfono: </label>
            <input type="number" name="tel" id="tel" value=""><br><br>     

            <label for="direccion">Dirección: </label>
            <input type="text" name="direccion" id="direccion" value=""><br><br>

            <label for="correo">Correo electrónico: </label>
            <input type="email" name="correo" id="correo" value=""><br><br>     

        </fieldset>
        <input type="submit" value="Crear">
        </form>
        <a href="{% url 'clientes:get' %}">Ir a la lista</a>
</body>
</html>

templates/clientes/cliente-detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cliente - {{ instancia.nombre }}</title>
</head>
<body>
    <h1>Instancia de Cliente</h1>
    <br>

    <ul>
        <li>{{ instancia.nombre }}</li>
        <li>{{ instancia.nit }}</li>
        <li>{{ instancia.nombre_contacto }}</li>
        <li>{{ instancia.telefono }}</li>
        <li>{{ instancia.correo }}</li>
        <li>{{ instancia.direccion }}</li>
    </ul>

</body>
</html>

templates/clientes/clientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clientes</title>
</head>
<body>
    <h1>Lista de Clientes</h1>
    <br>
    {% if lista_clientes %}
        <ul>
        {% for cl in lista_clientes %}
            <li><a href="{% url 'clientes:detail' cl.id %}">{{ cl.nombre }}     <a href="{% url 'clientes:delete' cl.id %}">X</a> </a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No existen clientes.</p>
    {% endif %}

    <a href="{% url 'clientes:create' %}">Crear Cliente</a>
</body>
</html>

templates/equipos/equipo-crear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equipo</title>
</head>
<body>
    <h1>Crear Equipo</h1>
    <br>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>
    
</body>
</html>

templates/equipos/equipo-detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equipo - {{ instancia.imei }}</title>
</head>
<body>
    <h1>Instancia de Equipo</h1>
    <br>

    <ul>
        <li><a href="{% url 'equipos:update' instancia.id %}">{{ instancia.imei }}</a></li>
        <li>{{ instancia.simcard }}</li>
        <li>{{ instancia.operador }}</li>
        <li>{{ instancia.activo }}</li>
        <li>{{ instancia.cliente }}</li>
    </ul>

</body>
</html>

templates/equipos/equipo_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

templates/equipos/equipos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equipos</title>
</head>
<body>
    <h1>Lista de Equipos</h1>
    <br>
    {% if object_list %}
        <ul>
        {% for eq in object_list %}
            <li><a href="{% url 'equipos:detail' eq.id %}">{{ eq.imei }}</a> <a href="{% url 'equipos:delete' eq.id %}">X</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No existen equipos.</p>
    {% endif %}

    <!-- <a href="{% url 'equipos:create' %}">Crear Equipo</a> -->
</body>
</html>